// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJG6_8GjYGRXLWizrrAii1043RCOHttIU',
    appId: '1:139279921943:web:4dd330d8a567e6e9b2fd52',
    messagingSenderId: '139279921943',
    projectId: 'aismartnoteapp',
    authDomain: 'aismartnoteapp.firebaseapp.com',
    storageBucket: 'aismartnoteapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7FGO3tiOaI7kJKHAI4TJHMnVxBcub-yA',
    appId: '1:139279921943:android:4fd3a36360ecd93cb2fd52',
    messagingSenderId: '139279921943',
    projectId: 'aismartnoteapp',
    storageBucket: 'aismartnoteapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3nJetxgdzwjeTbKvn36XrQ7PW589-0VQ',
    appId: '1:139279921943:ios:4b26e4d4ca615ef2b2fd52',
    messagingSenderId: '139279921943',
    projectId: 'aismartnoteapp',
    storageBucket: 'aismartnoteapp.firebasestorage.app',
    iosBundleId: 'com.example.aiSmartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3nJetxgdzwjeTbKvn36XrQ7PW589-0VQ',
    appId: '1:139279921943:ios:4b26e4d4ca615ef2b2fd52',
    messagingSenderId: '139279921943',
    projectId: 'aismartnoteapp',
    storageBucket: 'aismartnoteapp.firebasestorage.app',
    iosBundleId: 'com.example.aiSmartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJG6_8GjYGRXLWizrrAii1043RCOHttIU',
    appId: '1:139279921943:web:fe99bc9511b258d9b2fd52',
    messagingSenderId: '139279921943',
    projectId: 'aismartnoteapp',
    authDomain: 'aismartnoteapp.firebaseapp.com',
    storageBucket: 'aismartnoteapp.firebasestorage.app',
  );
}
